global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: urlshortener
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.1:8000', 'prometheus:9090']
