# Generated by Django 3.2.20 on 2023-07-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=500)),
                ('hash', models.CharField(db_index=True, max_length=10)),
                ('enabled', models.BooleanField()),
            ],
        ),
    ]
