# Generated by Django 3.2.20 on 2023-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='hash',
            field=models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
